config/routes.rb
May::Application.routes.draw do
  resources :articles

  devise_for :users

  root 'welcome#index'

  get '/login' => 'users#login'
  get '/bio' => 'welcome#bio'

      resources :users, :songs

      resources :articles do
        resources :comments
      end

  

end

app/models/Article.rb
class Article < ActiveRecord::Base
  belongs_to :User
  has_many :Comments
  #TODO - make photo accessible
  # attr_accessible :photo
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }
# From Paperclip install warning.  Necessary???
#   Paperclip 3.0 introduces a non-backward compatible change in your attachment
# path. This will help to prevent attachment name clashes when you have
# multiple attachments with the same name. If you didn't alter your
# attachment's path and are using Paperclip's default, you'll have to add
# `:path` and `:url` to your `has_attached_file` definition. For example:

#     has_attached_file :avatar,
#       :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
#       :url => "/system/:attachment/:id/:style/:filename"
end

app/models/Comment.rb
class Comment < ActiveRecord::Base
  belongs_to :User
  belongs_to :Article
end

app/models/Song.rb
class Song < ActiveRecord::Base
  
end

app/models/User.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
  has_many :comments

  #User Types
    # Admin -> profile_id: '1'
        # Privileges:  Can create, edit, or delete any content or user
    # Writer -> profile_id: '2'
        # Privileges:  Can create, edit, or delete own articles and comments
    # Visitor -> profile_id: '3'
        # Privileges:  Can create, edit, or delete own comments
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :User
  belongs_to :Article
end

app/models/song.rb
class Song < ActiveRecord::Base
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :user_id, :body, :keywords, :allow_comments, :photo)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    #Form to create a new user
    #For admins only - will have option to select type of user
  end

  def create
    #Creates new user account
    #Redirects to confirmation page upon successful account creation
  end

  def edit
    #Displays form for editing an existing user
    #Only admin level users can edit a user besides him/herself
  end

  def update
    #Applies changes from edit form
    #Redirects to confirmation page upon completion of successful changes
  end

  def show
  end

  def index
  end

  def delete
  end

  def confirmation
  end



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def login
  end

  def bio
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :user_id %>
    <%= f.input :body %>
    <%= f.input :keywords %>
    <%= f.input :allow_comments %>
    <%= f.input :photo %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th>Body</th>
      <th>Keywords</th>
      <th>Allow comments</th>
      <th>Photo</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.user_id %></td>
        <td><%= article.body %></td>
        <td><%= article.keywords %></td>
        <td><%= article.allow_comments %></td>
        <td><%= article.photo %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @article.user_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<p>
  <strong>Keywords:</strong>
  <%= @article.keywords %>
</p>

<p>
  <strong>Allow comments:</strong>
  <%= @article.allow_comments %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @article.photo %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class='nav'>
  <li> <%= link_to "Home", '/' %> </li>
  <li> <%= link_to "Music", songs_path  %> </li>
  <li> <%= link_to "Articles", articles_path  %> </li>
  <li> <%= link_to "Bio", bio_path %> </li>
</ul>


<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
    </li>
  <% else %>
    <li>
    <%= link_to('Login', new_user_session_path)  %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to('Edit account', edit_user_registration_path) %>
    </li>
  <% else %>
    <li>
    <%= link_to('Sign up', new_user_registration_path)  %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= yield :head %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <link href='http://fonts.googleapis.com/css?family=Permanent+Marker|Playfair+Display' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!-- Google Analytics Tracking Code -->
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <h1> Brian May Music </h1> 

      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <main role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/users/new.html.erb
<h1> Create a new user account </h1>

app/views/welcome/bio.html.erb
<h1> Bio </h1>

app/views/welcome/index.html.erb
<% content_for :head do %> 
  <meta title="Brian May">
  <meta name="description" content="Original worship songs by Brian May with downloadable chord charts and mp3 files.">
<% end %>


<h1> Home Page </h1>

app/views/welcome/login.html.erb
    <!-- From Bootstrap example template (responsive) -->
    <div class="container">

      <form class="form-signin">
        <h2 class="form-signin-heading">Please sign in</h2>
        <input type="text" class="input-block-level" placeholder="User Name">
        <input type="password" class="input-block-level" placeholder="Password">
        <label class="checkbox">
        <input type="checkbox" value="remember-me"> Remember me
        </label>
        <button class="btn btn-large btn-primary" type="submit">Sign in</button>
      </form>

    </div> <!-- /container -->